### PR TITLE
fix: crystal next compatibility

### PR DESCRIPTION
**Pull request by veelenga**
refs https://github.com/crystal-lang/crystal/pull/11597 
fixes https://github.com/crystal-ameba/ameba/issues/406

cc @straight-shoota

### CODE REVIEW

**Review by Sija — COMMENTED** [review]
`Lint/UselessAssign` rule is using `transformed?`, just fyi

**Comment by veelenga** [comment]
> `Lint/UselessAssign` rule is using `transformed?`, just fyi

Exactly, I left it for BC. It is not needed anymore for Crystal master and above.

**Comment by Sija** [comment]
@veelenga Could you please explain what do you mean by BC in this particular case? And why it's not longer needed?

**Comment by veelenga** [comment]
@Sija, sure.

In this PR, we've introduced support for Crystal's master version and subsequent versions. The term "BC" refers to the backward compatibility of Crystal (1.9.x) and earlier versions.

We implemented the `transformed?` method to determine if a node represents an assignment transformed by a compiler. To illustrate, in Crystal 1.9.x, the following code:

```crystal
collection.each do |(a, b)|
  puts b
end
```

is transformed before the AST phase to:

```crystal
collection.each do |__arg0|
  a = __arg0[0]
  b = __arg0[1]
  puts(b)
end
```

This transformation leads to false positives since the assignment to the variable `a` becomes redundant. So we had to handle that case "manually" via `#transformed?` method. 

However, in the Crystal master, the block mentioned above remains unaltered, and the resulting AST mirrors the original code:

```crystal
collection.each do |(a, b)|
  puts(b)
end
```

Consequently, for the Crystal master and later versions, the `transformed?` method becomes unnecessary. However, I suggest retaining this method until the next release for the sake of backward compatibility. This ensures that users using both Ameba's master and Crystal 1.9.x will still not encounter these false positives. 

--- 

I hope this revised version provides clarity and a more polished tone.

**Comment by veelenga** [comment]
@Sija, sure.

In this PR, we've introduced support for Crystal's master version and subsequent versions. The term "BC" refers to the backward compatibility of Crystal (1.9.x) and earlier versions.

We implemented the `transformed?` method to determine if a node represents an assignment transformed by a compiler. To illustrate, in Crystal 1.9.x, the following code:

```crystal
collection.each do |(a, b)|
  puts b
end
```

is transformed before the AST phase to:

```crystal
collection.each do |__arg0|
  a = __arg0[0]
  b = __arg0[1]
  puts(b)
end
```

This transformation leads to false positives since the assignment to the variable `a` becomes redundant. So we had to handle that case "manually" via `#transformed?` method. 

However, in the Crystal master, the block mentioned above remains unaltered, and the resulting AST mirrors the original code:

```crystal
collection.each do |(a, b)|
  puts(b)
end
```

Consequently, for the Crystal master and later versions, the `transformed?` method becomes unnecessary. However, I suggest retaining this method until the next release for the sake of backward compatibility. This ensures that users using both Ameba's master and Crystal 1.9.x will still not encounter these false positives.

**Comment by Sija** [comment]
@veelenga Thanks for the thorough explanation ❤️ It all makes sense, let's have this shipped then! :shipit:

**Review by Sija — APPROVED** [review]

**Pull request merged**
