### PR TITLE
Make `Lint/NotNilAfterNoBang` report calls to `#rindex`

### PR DESCRIPTION
**Pull request by Sija**
Requires Crystal 1.7.0

### CODE REVIEW

**Review by veelenga — APPROVED** [review]
LGTM. Should we drop support of Crystal 1.6 once this is merged?

**Comment by Sija** [comment]
@veelenga yup, I'd release `1.4.0` as the last release supporting Crystal <= 1.6 and use `1.5.0` for Crystal 1.7+ support.

**Comment by veelenga** [comment]
Sounds good to me. When you think we are ready to release?

**Comment by veelenga** [comment]
@Sija are we good merging this and release?

**Comment by Sija** [comment]
@veelenga This should go into `1.5.0`.

**Pull request merged**
