### PR TITLE
v0.14.4

### PR DESCRIPTION
**Pull request by Sija**
Bug-fix release fixing incorrect `crystal` version constraint.

### CODE REVIEW

**Comment by veelenga** [comment]
I would probably release 0.15 and include the new version constraint. And once Crystal 1.4 is available, release Ameba v1.0 and move to a semver. What do you think? @Sija

**Comment by Sija** [comment]
@veelenga WDYT about releasing `0.14.4` with `crystal` constain explicitly below 1.4? This way it wouldn't install instead of hanging CI.

**Comment by veelenga** [comment]
@Sija good idea. Would you mind preparing a branch for 0.14.4?

**Comment by Sija** [comment]
@veelenga here you go: https://github.com/crystal-ameba/ameba/tree/release/0.14.4

**Comment by veelenga** [comment]
Thanks. Made a new release: https://github.com/crystal-ameba/ameba/releases/tag/v0.14.4

**Pull request closed without merging**
